/**
 * The IconMap and Icons are generated by Claude Code but the method in which it is using
 *   is my design. Just used to speed up the process
 */

import { type ComponentType } from "react";
import { type IconProps } from "./BaseIcon";
import {
  SearchIcon,
  CloseIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ExternalLinkIcon,
} from "./Icons";

export const iconMap = {
  search: SearchIcon,
  close: CloseIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-left": ChevronLeftIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  check: CheckIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-left": ArrowLeftIcon,
  "external-link": ExternalLinkIcon,
} satisfies Record<string, ComponentType<IconProps>>;

export type IconName = keyof typeof iconMap;
